%% Perform image segmentation using several different algorithms.
%
% Inputs:
%     Im - An image on which segmentation shall be performed.
%     'Algorithm' - Which algorithm to use for segmentations.
%         Must be one of 'Kmeans', 'SOM', 'FCM', 'Spectral', 'GMM'.
%     'ImType' - Which type of image was provided. Either 'RGB' for an 
%        RGB image or 'Hyper' for a hyperspectral image.
%     'NumClusts' - The number of segments desired. Must be between 1
%         and 0.25 * N, where N is the number of pixels in Im.
%         If 1 is specified then round(0.05 * N) is used.
%
% Output:
%     ClusterIm - The labeled image generated by the clustering algorithm.
%     CCIm - If ImType is RGB then this variable contains the connected
%         components of the labeled image. Otherwise, CCIm is empty.
%
% Author: Matthew Carr
function [ClusterIm, CCIm] = MyClust6(Im, varargin)
    Algorithm = '';
    ImType = '';
    NumClusts = -1;
    
    % Extract input parameters from varargin.
    for i = 1:length(varargin)
        if strcmp(varargin(i), 'Algorithm')
            Algorithm = varargin{i + 1};
            i = i + 1;
        elseif strcmp(varargin(i), 'ImType')
            ImType = varargin{i + 1};
            i = i + 1;
        elseif strcmp(varargin(i), 'NumClusts')
            NumClusts = varargin{i + 1};
            i = i + 1;
        end
    end
    
    % Do some trivial input validation.
	
    if ~( strcmp(ImType, 'RGB') || strcmp(ImType, 'Hyper') )
        error('The ImType argument must be either "RGB" or "Hyper".');
    end
    
    [nrows, ncols, ~] = size(Im);
    npixels = nrows * ncols;
    if NumClusts <= 0 || NumClusts > 0.25 * npixels
        error(strcat( ...
            'The NumClusts argument must be between 1 and 0.25 times the ' ...
            , 'number of pixels in Im.' ...
        ));
	elseif NumClusts == 1
		NumClusts = round(0.05 * npixels);
    end
    
    % Call the named algorithm or error out.
    if strcmp(Algorithm, 'Kmeans')
        [ClusterIm, CCIm] = MyKmeans6(Im, ImType, NumClusts);
    elseif strcmp(Algorithm, 'SOM')
        [ClusterIm, CCIm] = MySOM6(Im, ImType, NumClusts);
    elseif strcmp(Algorithm, 'FCM')
        [ClusterIm, CCIm] = MyFCM6(Im, ImType, NumClusts);
    elseif strcmp(Algorithm, 'Spectral')
        [ClusterIm, CCIm] = MySpectral6(Im, ImType, NumClusts);
    elseif strcmp(Algorithm, 'GMM')
        [ClusterIm, CCIm] = MyGMM6(Im, ImType, NumClusts);
    else
        error('The Algorithm argument must be one of "Kmeans", "SOM", "FCM", "Spectral", or "GMM".');
    end
end